[package]
name = "libchess"
version = "0.7.0"
edition = "2021"
authors = ["Stanislav Khristoforov <stanislav.khristoforov@ya.ru>"]
description = "Simple Rust library to simulate the game of chess"
keywords = ["game", "rust", "chess", "chess-game", "chess-board"]
license = "MIT"

[dependencies]
colored = "2.0.0"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.7.1"
rustc-hash = "1.1.0"
textwrap = "0.16.0"
thiserror = "1.0.39"
