[package]
name = "libchess"
version = "0.1.0"
edition = "2021"
authors = ["Stanislav Khristoforov <stanislav.khristoforov@ya.ru>"]
description = "Simple Rust library to simulate the game of chess. No engine so far, just rules and legal moves"
keywords = ["chess"]
license = "MIT"

[dependencies]
colored = "2.0.0"
either = "1.6.1"
failure = "0.1.8"
lazy_static = "1.4.0"
unindent = "0.1.8"
