[package]
name = "libchess"
version = "0.5.1"
edition = "2021"
authors = ["Stanislav Khristoforov <stanislav.khristoforov@ya.ru>"]
description = "Simple Rust library to simulate the game of chess"
keywords = ["chess"]
license = "MIT"

[dependencies]
colored = "2.0.0"
lazy_static = "1.4.0"
rand = "0.8.5"
thiserror = "1.0.38"
