[package]
name = "libchess"
version = "0.4.6"
edition = "2021"
authors = ["Stanislav Khristoforov <stanislav.khristoforov@ya.ru>"]
description = "Simple Rust library to simulate the game of chess"
keywords = ["chess"]
license = "MIT"

[dependencies]
colored = "2.0.0"
failure = "0.1.8"
lazy_static = "1.4.0"
rand = "0.8.5"
